-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 16:40:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dojos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dojos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `location` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `id` INT NOT NULL,
  `dojo_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_dojos_dojo_id_idx` (`dojo_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_dojos_dojo_id`
    FOREIGN KEY (`dojo_id`)
    REFERENCES `mydb`.`dojos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `idaddress` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students_address` (
  `idstudents_address` INT NOT NULL,
  `id_student` INT NOT NULL,
  `id_addres` INT NOT NULL,
  PRIMARY KEY (`idstudents_address`),
  INDEX `fk_students_address:_students_id_students_idx` (`id_student` ASC) VISIBLE,
  INDEX `fk_students_address:_address_id_address_idx` (`id_addres` ASC) VISIBLE,
  CONSTRAINT `fk_students_address:_students_id_students`
    FOREIGN KEY (`id_student`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_address:_address_id_address`
    FOREIGN KEY (`id_addres`)
    REFERENCES `mydb`.`address` (`idaddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interests` (
  `idinterests` INT NOT NULL,
  `interests` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`idinterests`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students_interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students_interests` (
  `idstudents_interests` INT NOT NULL,
  `id_student` INT NOT NULL,
  `id_interest` INT NOT NULL,
  PRIMARY KEY (`idstudents_interests`),
  INDEX `fk_students_interests_students_id_student_idx` (`id_student` ASC) VISIBLE,
  INDEX `fk_students_interests_interests_id_interest_idx` (`id_interest` ASC) VISIBLE,
  CONSTRAINT `fk_students_interests_students_id_student`
    FOREIGN KEY (`id_student`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_interests_interests_id_interest`
    FOREIGN KEY (`id_interest`)
    REFERENCES `mydb`.`interests` (`idinterests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
